version: 2
updates:
  # Maintain root dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      # Group all npm root updates into one PR
      all-npm-root-dependencies:
        patterns:
          - "*"

  # Maintain backend dependencies
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      # Group all backend updates into one PR
      all-backend-dependencies:
        patterns:
          - "*"

  # Maintain GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      # Group all action updates into one PR
      all-actions:
        patterns:
          - "*"
